sudo: false
language: generic

env:
  - CXX="g++-4.7"
  - CXX="g++-4.7" CPP11="-DCPP11:int=1"
  - CXX="g++-4.8"
  - CXX="g++-4.8" CPP11="-DCPP11:int=1"
  - CXX="g++-4.9"
  - CXX="g++-4.9" CPP11="-DCPP11:int=1"
  - CXX="g++-5"
  - CXX="g++-5" CPP11="-DCPP11:int=1"
  - CXX="clang++-3.6"
  - CXX="clang++-3.6" CPP11="-DCPP11:int=1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.6
      - g++-4.7
      - g++-4.8
      - g++-4.9
      - g++-5
      - clang-3.6

before_install:
  - wget https://github.com/google/googletest/archive/release-1.7.0.zip && unzip release-1.7.0.zip && (cd googletest-release-1.7.0 && cmake . && make)
  - export GTEST_ROOT=${TRAVIS_BUILD_DIR}/googletest-release-1.7.0
  - if [ -z "$CPP11" ]; then wget http://freefr.dl.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.zip && unzip boost_1_55_0.zip > /dev/null && export BOOST_ROOT=boost_1_55_0; fi

script:
  - ${CXX} --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. ${CPP11} && make VERBOSE=1 && ./minijson_reader_tests
